import Head from 'next/head'
import Image from 'next/image'
import Tag from '../components/tag'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sharon Bach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {/* Projects */}
        <section id="intro">
          <h1>Sharon Bach is a graphic designer working on identity, interactive and web design. She is currently the cofounder and art director at creative studio 13milliseconds. She lives in Upstate New York.</h1>
          <Tag>Mural</Tag>
          <Tag>Interface</Tag>
          <Tag>Packaging</Tag>
          <Tag>Branding</Tag>
          <Tag>Web design</Tag>
        </section>

        {/* Projects */}
        <section id="bottomSection">
          <div className="uk-container">
            <h2>Projects</h2>
          </div>
        </section>

        {/* Bottom */}
        <section id="bottomSection">
          <div className="uk-container">
            <div className="uk-grid">
              <div id="bio">
                <h2>About</h2>
              </div>
              <div id="clients">
                <h2>Clients</h2>
              </div>
            </div>
          </div>
        </section>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
